/* Automatically generated by
	SmartSyntaxPluginCodeGenerator VMMaker-oscog-HolgerHansPeterFreyther.309 uuid: d6bc40bb-b96a-497b-8c00-564713877f19
   from
	SocketPlugin VMMaker-oscog-HolgerHansPeterFreyther.309 uuid: d6bc40bb-b96a-497b-8c00-564713877f19
 */
static char __buildInfo[] = "SocketPlugin VMMaker-oscog-HolgerHansPeterFreyther.309 uuid: d6bc40bb-b96a-497b-8c00-564713877f19 " __DATE__ ;



#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

/* Default EXPORT macro that does nothing (see comment in sq.h): */
#define EXPORT(returnType) returnType

/* Do not include the entire sq.h file but just those parts needed. */
/*  The virtual machine proxy definition */
#include "sqVirtualMachine.h"
/* Configuration options */
#include "sqConfig.h"
/* Platform specific definitions */
#include "sqPlatformSpecific.h"

#define true 1
#define false 0
#define null 0  /* using 'null' because nil is predefined in Think C */
#ifdef SQUEAK_BUILTIN_PLUGIN
#undef EXPORT
// was #undef EXPORT(returnType) but screws NorCroft cc
#define EXPORT(returnType) static returnType
#endif

#include "SocketPlugin.h"
#include "sqMemoryAccess.h"


/*** Constants ***/
#define BytesPerWord 4


/*** Function Prototypes ***/
static VirtualMachine * getInterpreter(void);
EXPORT(const char*) getModuleName(void);
static sqInt halt(void);
EXPORT(sqInt) initialiseModule(void);
static sqInt intToNetAddress(sqInt addr);
EXPORT(void) moduleUnloaded(char *aModuleName);
static sqInt msg(char *s);
static sqInt netAddressToInt(unsigned char *  ptrToByteArray);
EXPORT(void) primitiveDisableSocketAccess(void);
EXPORT(void) primitiveHasSocketAccess(void);
EXPORT(sqInt) primitiveInitializeNetwork(void);
EXPORT(sqInt) primitiveResolverAbortLookup(void);
EXPORT(sqInt) primitiveResolverAddressLookupResult(void);
EXPORT(sqInt) primitiveResolverError(void);
EXPORT(sqInt) primitiveResolverGetAddressInfo(void);
EXPORT(sqInt) primitiveResolverGetAddressInfoFamily(void);
EXPORT(sqInt) primitiveResolverGetAddressInfoNext(void);
EXPORT(sqInt) primitiveResolverGetAddressInfoProtocol(void);
EXPORT(sqInt) primitiveResolverGetAddressInfoResult(void);
EXPORT(sqInt) primitiveResolverGetAddressInfoSize(void);
EXPORT(sqInt) primitiveResolverGetAddressInfoType(void);
EXPORT(sqInt) primitiveResolverGetNameInfo(void);
EXPORT(sqInt) primitiveResolverGetNameInfoHostResult(void);
EXPORT(sqInt) primitiveResolverGetNameInfoHostSize(void);
EXPORT(sqInt) primitiveResolverGetNameInfoServiceResult(void);
EXPORT(sqInt) primitiveResolverGetNameInfoServiceSize(void);
EXPORT(sqInt) primitiveResolverHostNameResult(void);
EXPORT(sqInt) primitiveResolverHostNameSize(void);
EXPORT(sqInt) primitiveResolverLocalAddress(void);
EXPORT(sqInt) primitiveResolverNameLookupResult(void);
EXPORT(sqInt) primitiveResolverStartAddressLookup(void);
EXPORT(sqInt) primitiveResolverStartNameLookup(void);
EXPORT(sqInt) primitiveResolverStatus(void);
EXPORT(sqInt) primitiveSocketAbortConnection(void);
EXPORT(sqInt) primitiveSocketAccept(void);
EXPORT(sqInt) primitiveSocketAccept3Semaphores(void);
EXPORT(sqInt) primitiveSocketAddressGetPort(void);
EXPORT(sqInt) primitiveSocketAddressSetPort(void);
EXPORT(sqInt) primitiveSocketBindTo(void);
EXPORT(sqInt) primitiveSocketBindToPort(void);
EXPORT(sqInt) primitiveSocketCloseConnection(void);
EXPORT(sqInt) primitiveSocketConnectionStatus(void);
EXPORT(sqInt) primitiveSocketConnectTo(void);
EXPORT(sqInt) primitiveSocketConnectToPort(void);
EXPORT(sqInt) primitiveSocketCreate(void);
EXPORT(sqInt) primitiveSocketCreate3Semaphores(void);
EXPORT(sqInt) primitiveSocketDestroy(void);
EXPORT(sqInt) primitiveSocketError(void);
EXPORT(sqInt) primitiveSocketGetOptions(void);
EXPORT(sqInt) primitiveSocketListenOnPort(void);
EXPORT(sqInt) primitiveSocketListenOnPortBacklog(void);
EXPORT(sqInt) primitiveSocketListenOnPortBacklogInterface(void);
EXPORT(sqInt) primitiveSocketListenWithBacklog(void);
EXPORT(sqInt) primitiveSocketListenWithOrWithoutBacklog(void);
EXPORT(sqInt) primitiveSocketLocalAddress(void);
EXPORT(sqInt) primitiveSocketLocalAddressResult(void);
EXPORT(sqInt) primitiveSocketLocalAddressSize(void);
EXPORT(sqInt) primitiveSocketLocalPort(void);
EXPORT(sqInt) primitiveSocketReceiveDataAvailable(void);
EXPORT(sqInt) primitiveSocketReceiveDataBufCount(void);
EXPORT(sqInt) primitiveSocketReceiveUDPDataBufCount(void);
EXPORT(sqInt) primitiveSocketRemoteAddress(void);
EXPORT(sqInt) primitiveSocketRemoteAddressResult(void);
EXPORT(sqInt) primitiveSocketRemoteAddressSize(void);
EXPORT(sqInt) primitiveSocketRemotePort(void);
EXPORT(sqInt) primitiveSocketSCTPEnableDataIOEvent(void);
EXPORT(sqInt) primitiveSocketSCTPReceive(void);
EXPORT(sqInt) primitiveSocketSCTPSend(void);
EXPORT(sqInt) primitiveSocketSendDataBufCount(void);
EXPORT(sqInt) primitiveSocketSendDone(void);
EXPORT(sqInt) primitiveSocketSendUDPDataBufCount(void);
EXPORT(sqInt) primitiveSocketSetOptions(void);
EXPORT(sqInt) setInterpreter(struct VirtualMachine*anInterpreter);
EXPORT(sqInt) shutdownModule(void);
static sqInt socketRecordSize(void);
static sqInt socketSCTPSndRcvInfoSize(void);
static SocketPtr socketValueOf(sqInt socketOop);
static void sqAssert(sqInt aBool);


/*** Variables ***/

#if !defined(SQUEAK_BUILTIN_PLUGIN)
static sqInt (*byteSizeOf)(sqInt oop);
static sqInt (*classArray)(void);
static sqInt (*classByteArray)(void);
static sqInt (*classString)(void);
static sqInt (*failed)(void);
static sqInt (*falseObject)(void);
static void * (*firstIndexableField)(sqInt oop);
static sqInt (*instantiateClassindexableSize)(sqInt classPointer, sqInt size);
static sqInt (*integerObjectOf)(sqInt value);
static void * (*ioLoadFunctionFrom)(char *functionName, char *moduleName);
static sqInt (*isBytes)(sqInt oop);
static sqInt (*isWords)(sqInt oop);
static sqInt (*isWordsOrBytes)(sqInt oop);
static sqInt (*methodArgumentCount)(void);
static sqInt (*pop)(sqInt nItems);
static sqInt (*popthenPush)(sqInt nItems, sqInt oop);
static sqInt (*popRemappableOop)(void);
static sqInt (*primitiveFail)(void);
static sqInt (*pushBool)(sqInt trueOrFalse);
static sqInt (*pushRemappableOop)(sqInt oop);
static sqInt (*slotSizeOf)(sqInt oop);
static sqInt (*stackIntegerValue)(sqInt offset);
static sqInt (*stackValue)(sqInt offset);
static sqInt (*storePointerofObjectwithValue)(sqInt index, sqInt oop, sqInt valuePointer);
static sqInt (*success)(sqInt aBoolean);
static sqInt (*trueObject)(void);
#else /* !defined(SQUEAK_BUILTIN_PLUGIN) */
extern sqInt byteSizeOf(sqInt oop);
extern sqInt classArray(void);
extern sqInt classByteArray(void);
extern sqInt classString(void);
extern sqInt failed(void);
extern sqInt falseObject(void);
extern void * firstIndexableField(sqInt oop);
extern sqInt instantiateClassindexableSize(sqInt classPointer, sqInt size);
extern sqInt integerObjectOf(sqInt value);
extern void * ioLoadFunctionFrom(char *functionName, char *moduleName);
extern sqInt isBytes(sqInt oop);
extern sqInt isWords(sqInt oop);
extern sqInt isWordsOrBytes(sqInt oop);
extern sqInt methodArgumentCount(void);
extern sqInt pop(sqInt nItems);
extern sqInt popthenPush(sqInt nItems, sqInt oop);
extern sqInt popRemappableOop(void);
extern sqInt primitiveFail(void);
extern sqInt pushBool(sqInt trueOrFalse);
extern sqInt pushRemappableOop(sqInt oop);
extern sqInt slotSizeOf(sqInt oop);
extern sqInt stackIntegerValue(sqInt offset);
extern sqInt stackValue(sqInt offset);
extern sqInt storePointerofObjectwithValue(sqInt index, sqInt oop, sqInt valuePointer);
extern sqInt success(sqInt aBoolean);
extern sqInt trueObject(void);

extern
#endif
struct VirtualMachine* interpreterProxy;
static const char *moduleName =
#ifdef SQUEAK_BUILTIN_PLUGIN
	"SocketPlugin VMMaker-oscog-HolgerHansPeterFreyther.309 (i)"
#else
	"SocketPlugin VMMaker-oscog-HolgerHansPeterFreyther.309 (e)"
#endif
;
static void * sCCLOPfn;
static void * sCCSOTfn;
static void * sCCTPfn;
static void * sDSAfn;
static void * sHSAfn;



/*	Note: This is coded so that plugins can be run from Squeak. */

static VirtualMachine *
getInterpreter(void)
{
	// InterpreterPlugin>>#getInterpreter
	return interpreterProxy;
}


/*	Note: This is hardcoded so it can be run from Squeak.
	The module name is used for validating a module *after*
	it is loaded to check if it does really contain the module
	we're thinking it contains. This is important! */

EXPORT(const char*)
getModuleName(void)
{
	// InterpreterPlugin>>#getModuleName
	return moduleName;
}

static sqInt
halt(void)
{
	// InterpreterPlugin>>#halt
	;
	return 0;
}

EXPORT(sqInt)
initialiseModule(void)
{
	// SocketPlugin>>#initialiseModule
	sDSAfn = ioLoadFunctionFrom("secDisableSocketAccess", "SecurityPlugin");
	sHSAfn = ioLoadFunctionFrom("secHasSocketAccess", "SecurityPlugin");
	sCCTPfn = ioLoadFunctionFrom("secCanConnectToPort", "SecurityPlugin");
	sCCLOPfn = ioLoadFunctionFrom("secCanListenOnPort", "SecurityPlugin");
	sCCSOTfn = ioLoadFunctionFrom("secCanCreateSocketOfType", "SecurityPlugin");
	return socketInit();
}


/*	Convert the given 32-bit integer into an internet network address
	represented as a four-byte ByteArray.
 */

static sqInt
intToNetAddress(sqInt addr)
{
	// SocketPlugin>>#intToNetAddress:
	char *  naPtr;
	sqInt netAddressOop;

	netAddressOop = instantiateClassindexableSize(classByteArray(), 4);
	naPtr = ((char *)firstIndexableField(netAddressOop));
	naPtr[0] = (((char) ((((usqInt) addr) >> 24) & 255)));
	naPtr[1] = (((char) ((((usqInt) addr) >> 16) & 255)));
	naPtr[2] = (((char) ((((usqInt) addr) >> 8) & 255)));
	naPtr[3] = (((char) (addr & 255)));
	return netAddressOop;
}


/*	The module with the given name was just unloaded.
	Make sure we have no dangling references. */

EXPORT(void)
moduleUnloaded(char *aModuleName)
{
	// SocketPlugin>>#moduleUnloaded:
	if ((strcmp(aModuleName, "SecurityPlugin")) == 0) {

		/* The security plugin just shut down. How odd. */

sDSAfn = (sHSAfn = (sCCTPfn = (sCCLOPfn = (sCCSOTfn = 0))));
	}
}

static sqInt
msg(char *s)
{
	// InterpreterPlugin>>#msg:
	fprintf(stderr, "\n%s: %s", moduleName, s);
	return 0;
}


/*	Convert the given internet network address (represented as a four-byte
	ByteArray) into a 32-bit integer. Fail if the given ptrToByteArray does
	not appear to point to a four-byte ByteArray.
 */

static sqInt
netAddressToInt(unsigned char *  ptrToByteArray)
{
	// SocketPlugin>>#netAddressToInt:
	sqInt sz;

	sz = byteSizeOf(((sqInt)(long)(ptrToByteArray) - 4));
	if (!(sz == 4)) {
		return primitiveFail();
	}
	return (((ptrToByteArray[3]) + ((ptrToByteArray[2]) << 8)) + ((ptrToByteArray[1]) << 16)) + ((ptrToByteArray[0]) << 24);
}


/*	If the security plugin can be loaded, use it to turn off socket access
	If not, assume it's ok */

EXPORT(void)
primitiveDisableSocketAccess(void)
{
	// SocketPlugin>>#primitiveDisableSocketAccess
	if (sDSAfn != 0) {
((int (*) (void)) sDSAfn)();
	}
}

EXPORT(void)
primitiveHasSocketAccess(void)
{
	// SocketPlugin>>#primitiveHasSocketAccess
	sqInt hasAccess;


	/* If the security plugin can be loaded, use it to check .
	   If not, assume it's ok */

	if (sHSAfn != 0) {

		/* If the security plugin can be loaded, use it to check .
		   If not, assume it's ok */

		hasAccess =  ((int (*) (void)) sHSAfn)();
	}
	else {
hasAccess = 1;
	}
	pop(1);
	pushBool(hasAccess);
}

EXPORT(sqInt)
primitiveInitializeNetwork(void)
{
	// SocketPlugin>>#primitiveInitializeNetwork
	sqInt err;
	sqInt resolverSemaIndex;

	resolverSemaIndex = stackIntegerValue(0);
	if (failed()) {
		return null;
	}
	err = sqNetworkInit(resolverSemaIndex);
	success(err == 0);
	if (failed()) {
		return null;
	}
	pop(1);
	return null;
}

EXPORT(sqInt)
primitiveResolverAbortLookup(void)
{
	// SocketPlugin>>#primitiveResolverAbortLookup
	sqResolverAbort();
	if (failed()) {
		return null;
	}
	return null;
}

EXPORT(sqInt)
primitiveResolverAddressLookupResult(void)
{
	// SocketPlugin>>#primitiveResolverAddressLookupResult
	sqInt s;
	sqInt sz;

	sz = sqResolverAddrLookupResultSize();
	if (!(failed())) {
		s = instantiateClassindexableSize(classString(), sz);
		sqResolverAddrLookupResult(((char *)firstIndexableField(s)), sz);
	}
	if (failed()) {
		return null;
	}
	popthenPush(1, s);
	return null;
}

EXPORT(sqInt)
primitiveResolverError(void)
{
	// SocketPlugin>>#primitiveResolverError
	sqInt _return_value;

	_return_value = integerObjectOf((sqResolverError()));
	if (failed()) {
		return null;
	}
	popthenPush(1, _return_value);
	return null;
}

EXPORT(sqInt)
primitiveResolverGetAddressInfo(void)
{
	// SocketPlugin>>#primitiveResolverGetAddressInfo
	sqInt family;
	sqInt flags;
	char *hostName;
	sqInt hostSize;
	sqInt protocol;
	char *servName;
	sqInt servSize;
	sqInt type;

	success(isBytes(stackValue(5)));
	hostName = ((char *) (firstIndexableField(stackValue(5))));
	success(isBytes(stackValue(4)));
	servName = ((char *) (firstIndexableField(stackValue(4))));
	flags = stackIntegerValue(3);
	family = stackIntegerValue(2);
	type = stackIntegerValue(1);
	protocol = stackIntegerValue(0);
	if (failed()) {
		return null;
	}
	if (!(failed())) {
		hostSize = byteSizeOf(((sqInt)(long)(hostName) - 4));
		servSize = byteSizeOf(((sqInt)(long)(servName) - 4));
		sqResolverGetAddressInfoHostSizeServiceSizeFlagsFamilyTypeProtocol(hostName, hostSize, servName, servSize, flags, family, type, protocol);
	}
	if (failed()) {
		return null;
	}
	pop(6);
	return null;
}

EXPORT(sqInt)
primitiveResolverGetAddressInfoFamily(void)
{
	// SocketPlugin>>#primitiveResolverGetAddressInfoFamily
	sqInt family;
	sqInt _return_value;

	if (!(failed())) {
		family = sqResolverGetAddressInfoFamily();
		_return_value = integerObjectOf(family);
		if (failed()) {
			return null;
		}
		popthenPush(1, _return_value);
		return null;
	}
	if (failed()) {
		return null;
	}
	return null;
}

EXPORT(sqInt)
primitiveResolverGetAddressInfoNext(void)
{
	// SocketPlugin>>#primitiveResolverGetAddressInfoNext
	sqInt more;
	sqInt _return_value;

	more = sqResolverGetAddressInfoNext();
	if (failed()) {
		return null;
	}
	_return_value = ((more) ? trueObject() : falseObject());
	if (failed()) {
		return null;
	}
	popthenPush(1, _return_value);
	return null;
}

EXPORT(sqInt)
primitiveResolverGetAddressInfoProtocol(void)
{
	// SocketPlugin>>#primitiveResolverGetAddressInfoProtocol
	sqInt protocol;
	sqInt _return_value;

	if (!(failed())) {
		protocol = sqResolverGetAddressInfoProtocol();
		_return_value = integerObjectOf(protocol);
		if (failed()) {
			return null;
		}
		popthenPush(1, _return_value);
		return null;
	}
	if (failed()) {
		return null;
	}
	return null;
}

EXPORT(sqInt)
primitiveResolverGetAddressInfoResult(void)
{
	// SocketPlugin>>#primitiveResolverGetAddressInfoResult
	sqInt addrSize;
	char *socketAddress;

	success(isBytes(stackValue(0)));
	socketAddress = ((char *) (firstIndexableField(stackValue(0))));
	if (failed()) {
		return null;
	}
	if (!(failed())) {
		addrSize = byteSizeOf(((sqInt)(long)(socketAddress) - 4));
		sqResolverGetAddressInfoResultSize(socketAddress, addrSize);
	}
	if (failed()) {
		return null;
	}
	pop(1);
	return null;
}

EXPORT(sqInt)
primitiveResolverGetAddressInfoSize(void)
{
	// SocketPlugin>>#primitiveResolverGetAddressInfoSize
	sqInt size;
	sqInt _return_value;

	if (!(failed())) {
		size = sqResolverGetAddressInfoSize();
		_return_value = integerObjectOf(size);
		if (failed()) {
			return null;
		}
		popthenPush(1, _return_value);
		return null;
	}
	if (failed()) {
		return null;
	}
	return null;
}

EXPORT(sqInt)
primitiveResolverGetAddressInfoType(void)
{
	// SocketPlugin>>#primitiveResolverGetAddressInfoType
	sqInt type;
	sqInt _return_value;

	if (!(failed())) {
		type = sqResolverGetAddressInfoType();
		_return_value = integerObjectOf(type);
		if (failed()) {
			return null;
		}
		popthenPush(1, _return_value);
		return null;
	}
	if (failed()) {
		return null;
	}
	return null;
}

EXPORT(sqInt)
primitiveResolverGetNameInfo(void)
{
	// SocketPlugin>>#primitiveResolverGetNameInfo
	char *addrBase;
	sqInt addrSize;
	sqInt flags;
	sqInt socketAddress;

	socketAddress = stackValue(1);
	flags = stackIntegerValue(0);
	if (failed()) {
		return null;
	}
	if (!(failed())) {
		addrSize = byteSizeOf(socketAddress);
		addrBase = ((char *) (firstIndexableField(socketAddress)));
		sqResolverGetNameInfoSizeFlags(addrBase, addrSize, flags);
	}
	if (failed()) {
		return null;
	}
	pop(2);
	return null;
}

EXPORT(sqInt)
primitiveResolverGetNameInfoHostResult(void)
{
	// SocketPlugin>>#primitiveResolverGetNameInfoHostResult
	sqInt addrSize;
	char *socketName;

	success(isBytes(stackValue(0)));
	socketName = ((char *) (firstIndexableField(stackValue(0))));
	if (failed()) {
		return null;
	}
	if (!(failed())) {
		addrSize = byteSizeOf(((sqInt)(long)(socketName) - 4));
		sqResolverGetNameInfoHostResultSize(socketName, addrSize);
	}
	if (failed()) {
		return null;
	}
	pop(1);
	return null;
}

EXPORT(sqInt)
primitiveResolverGetNameInfoHostSize(void)
{
	// SocketPlugin>>#primitiveResolverGetNameInfoHostSize
	sqInt size;
	sqInt _return_value;

	if (!(failed())) {
		size = sqResolverGetNameInfoHostSize();
		_return_value = integerObjectOf(size);
		if (failed()) {
			return null;
		}
		popthenPush(1, _return_value);
		return null;
	}
	if (failed()) {
		return null;
	}
	return null;
}

EXPORT(sqInt)
primitiveResolverGetNameInfoServiceResult(void)
{
	// SocketPlugin>>#primitiveResolverGetNameInfoServiceResult
	sqInt addrSize;
	char *socketName;

	success(isBytes(stackValue(0)));
	socketName = ((char *) (firstIndexableField(stackValue(0))));
	if (failed()) {
		return null;
	}
	if (!(failed())) {
		addrSize = byteSizeOf(((sqInt)(long)(socketName) - 4));
		sqResolverGetNameInfoServiceResultSize(socketName, addrSize);
	}
	if (failed()) {
		return null;
	}
	pop(1);
	return null;
}

EXPORT(sqInt)
primitiveResolverGetNameInfoServiceSize(void)
{
	// SocketPlugin>>#primitiveResolverGetNameInfoServiceSize
	sqInt size;
	sqInt _return_value;

	if (!(failed())) {
		size = sqResolverGetNameInfoServiceSize();
		_return_value = integerObjectOf(size);
		if (failed()) {
			return null;
		}
		popthenPush(1, _return_value);
		return null;
	}
	if (failed()) {
		return null;
	}
	return null;
}

EXPORT(sqInt)
primitiveResolverHostNameResult(void)
{
	// SocketPlugin>>#primitiveResolverHostNameResult
	sqInt nameSize;
	char *nameString;

	success(isBytes(stackValue(0)));
	nameString = ((char *) (firstIndexableField(stackValue(0))));
	if (failed()) {
		return null;
	}
	if (!(failed())) {
		nameSize = byteSizeOf(((sqInt)(long)(nameString) - 4));
		sqResolverHostNameResultSize(nameString, nameSize);
	}
	if (failed()) {
		return null;
	}
	pop(1);
	return null;
}

EXPORT(sqInt)
primitiveResolverHostNameSize(void)
{
	// SocketPlugin>>#primitiveResolverHostNameSize
	sqInt size;
	sqInt _return_value;

	if (!(failed())) {
		size = sqResolverHostNameSize();
		if (!(failed())) {
			_return_value = integerObjectOf(size);
			if (failed()) {
				return null;
			}
			popthenPush(1, _return_value);
			return null;
		}
	}
	if (failed()) {
		return null;
	}
	return null;
}

EXPORT(sqInt)
primitiveResolverLocalAddress(void)
{
	// SocketPlugin>>#primitiveResolverLocalAddress
	sqInt addr;
	sqInt _return_value;

	addr = sqResolverLocalAddress();
	_return_value = intToNetAddress(addr);
	if (failed()) {
		return null;
	}
	popthenPush(1, _return_value);
	return null;
}

EXPORT(sqInt)
primitiveResolverNameLookupResult(void)
{
	// SocketPlugin>>#primitiveResolverNameLookupResult
	sqInt addr;
	sqInt _return_value;

	addr = sqResolverNameLookupResult();
	_return_value = intToNetAddress(addr);
	if (failed()) {
		return null;
	}
	popthenPush(1, _return_value);
	return null;
}

EXPORT(sqInt)
primitiveResolverStartAddressLookup(void)
{
	// SocketPlugin>>#primitiveResolverStartAddressLookup
	sqInt addr;
	char *address;
	sqInt sz;

	success(isBytes(stackValue(0)));
	address = ((char *) (firstIndexableField(stackValue(0))));
	if (failed()) {
		return null;
	}
	/* begin netAddressToInt: */
sz = byteSizeOf(((sqInt)(long)((((unsigned char *) address))) - 4));
	if (!(sz == 4)) {
		addr = primitiveFail();
		goto l1;
	}
	addr = ((((((unsigned char *) address))[3]) + (((((unsigned char *) address))[2]) << 8)) + (((((unsigned char *) address))[1]) << 16)) + (((((unsigned char *) address))[0]) << 24);
l1:	/* end netAddressToInt: */;
	if (!(failed())) {
		sqResolverStartAddrLookup(addr);
	}
	if (failed()) {
		return null;
	}
	pop(1);
	return null;
}

EXPORT(sqInt)
primitiveResolverStartNameLookup(void)
{
	// SocketPlugin>>#primitiveResolverStartNameLookup
	char *name;
	sqInt sz;

	success(isBytes(stackValue(0)));
	name = ((char *) (firstIndexableField(stackValue(0))));
	if (failed()) {
		return null;
	}
	if (!(failed())) {
		sz = byteSizeOf(((sqInt)(long)(name) - 4));
		sqResolverStartNameLookup(name, sz);
	}
	if (failed()) {
		return null;
	}
	pop(1);
	return null;
}

EXPORT(sqInt)
primitiveResolverStatus(void)
{
	// SocketPlugin>>#primitiveResolverStatus
	sqInt status;
	sqInt _return_value;

	status = sqResolverStatus();
	_return_value = integerObjectOf(status);
	if (failed()) {
		return null;
	}
	popthenPush(1, _return_value);
	return null;
}

EXPORT(sqInt)
primitiveSocketAbortConnection(void)
{
	// SocketPlugin>>#primitiveSocketAbortConnection
	SocketPtr  s;
	sqInt socket;

	socket = stackValue(0);
	if (failed()) {
		return null;
	}
	/* begin socketValueOf: */
success((isBytes(socket))
	 && ((byteSizeOf(socket)) == (socketRecordSize())));
	s = (failed()
		? null
		: ((SocketPtr) (firstIndexableField(socket))));
	if (!(failed())) {
		sqSocketAbortConnection(s);
	}
	if (failed()) {
		return null;
	}
	pop(1);
	return null;
}

EXPORT(sqInt)
primitiveSocketAccept(void)
{
	// SocketPlugin>>#primitiveSocketAccept
	sqInt recvBufSize;
	SocketPtr  s;
	sqInt semaIndex;
	sqInt sendBufSize;
	SocketPtr  serverSocket;
	sqInt socketOop;
	sqInt sockHandle;

	sockHandle = stackValue(3);
	recvBufSize = stackIntegerValue(2);
	sendBufSize = stackIntegerValue(1);
	semaIndex = stackIntegerValue(0);
	if (failed()) {
		return null;
	}
	/* begin socketValueOf: */
success((isBytes(sockHandle))
	 && ((byteSizeOf(sockHandle)) == (socketRecordSize())));
	serverSocket = (failed()
		? null
		: ((SocketPtr) (firstIndexableField(sockHandle))));
	if (!(failed())) {
		socketOop = instantiateClassindexableSize(classByteArray(), socketRecordSize());
		/* begin socketValueOf: */
success((isBytes(socketOop))
		 && ((byteSizeOf(socketOop)) == (socketRecordSize())));
		s = (failed()
			? null
			: ((SocketPtr) (firstIndexableField(socketOop))));
		sqSocketAcceptFromRecvBytesSendBytesSemaID(s, serverSocket, recvBufSize, sendBufSize, semaIndex);
	}
	if (failed()) {
		return null;
	}
	popthenPush(5, socketOop);
	return null;
}

EXPORT(sqInt)
primitiveSocketAccept3Semaphores(void)
{
	// SocketPlugin>>#primitiveSocketAccept3Semaphores
	sqInt aReadSema;
	sqInt aWriteSema;
	sqInt recvBufSize;
	SocketPtr  s;
	sqInt semaIndex;
	sqInt sendBufSize;
	SocketPtr  serverSocket;
	sqInt socketOop;
	sqInt sockHandle;

	sockHandle = stackValue(5);
	recvBufSize = stackIntegerValue(4);
	sendBufSize = stackIntegerValue(3);
	semaIndex = stackIntegerValue(2);
	aReadSema = stackIntegerValue(1);
	aWriteSema = stackIntegerValue(0);
	if (failed()) {
		return null;
	}
	/* begin socketValueOf: */
success((isBytes(sockHandle))
	 && ((byteSizeOf(sockHandle)) == (socketRecordSize())));
	serverSocket = (failed()
		? null
		: ((SocketPtr) (firstIndexableField(sockHandle))));
	if (!(failed())) {
		socketOop = instantiateClassindexableSize(classByteArray(), socketRecordSize());
		/* begin socketValueOf: */
success((isBytes(socketOop))
		 && ((byteSizeOf(socketOop)) == (socketRecordSize())));
		s = (failed()
			? null
			: ((SocketPtr) (firstIndexableField(socketOop))));
		sqSocketAcceptFromRecvBytesSendBytesSemaIDReadSemaIDWriteSemaID(s, serverSocket, recvBufSize, sendBufSize, semaIndex, aReadSema, aWriteSema);
	}
	if (failed()) {
		return null;
	}
	popthenPush(7, socketOop);
	return null;
}

EXPORT(sqInt)
primitiveSocketAddressGetPort(void)
{
	// SocketPlugin>>#primitiveSocketAddressGetPort
	sqInt addr;
	char *addrBase;
	sqInt addrSize;
	sqInt port;
	sqInt _return_value;

	addr = stackValue(0);
	if (failed()) {
		return null;
	}
	addrSize = byteSizeOf(addr);
	addrBase = ((char *) (firstIndexableField(addr)));
	if (!(failed())) {
		port = sqSocketAddressSizeGetPort(addrBase, addrSize);
		if (!(failed())) {
			_return_value = integerObjectOf(port);
			if (failed()) {
				return null;
			}
			popthenPush(1, _return_value);
			return null;
		}
	}
	if (failed()) {
		return null;
	}
	return null;
}

EXPORT(sqInt)
primitiveSocketAddressSetPort(void)
{
	// SocketPlugin>>#primitiveSocketAddressSetPort
	sqInt addr;
	char *addrBase;
	sqInt addrSize;
	sqInt portNumber;

	portNumber = stackIntegerValue(0);
	addr = stackValue(1);
	if (failed()) {
		return null;
	}
	addrSize = byteSizeOf(addr);
	addrBase = ((char *) (firstIndexableField(addr)));
	if (!(failed())) {
		sqSocketAddressSizeSetPort(addrBase, addrSize, portNumber);
	}
	if (failed()) {
		return null;
	}
	pop(1);
	return null;
}

EXPORT(sqInt)
primitiveSocketBindTo(void)
{
	// SocketPlugin>>#primitiveSocketBindTo
	char *addrBase;
	sqInt addrSize;
	SocketPtr s;
	sqInt socket;
	sqInt socketAddress;

	socket = stackValue(1);
	socketAddress = stackValue(0);
	if (failed()) {
		return null;
	}
	/* begin socketValueOf: */
success((isBytes(socket))
	 && ((byteSizeOf(socket)) == (socketRecordSize())));
	s = (failed()
		? null
		: ((SocketPtr) (firstIndexableField(socket))));
	addrSize = byteSizeOf(socketAddress);
	addrBase = ((char *) (firstIndexableField(socketAddress)));
	if (!(failed())) {
		sqSocketBindToAddressSize(s, addrBase, addrSize);
	}
	if (failed()) {
		return null;
	}
	pop(2);
	return null;
}

EXPORT(sqInt)
primitiveSocketBindToPort(void)
{
	// SocketPlugin>>#primitiveSocketBindToPort
	sqInt addr;
	char *address;
	sqInt port;
	SocketPtr s;
	sqInt socket;
	sqInt sz;

	socket = stackValue(2);
	success(isBytes(stackValue(1)));
	address = ((char *) (firstIndexableField(stackValue(1))));
	port = stackIntegerValue(0);
	if (failed()) {
		return null;
	}
	/* begin netAddressToInt: */
sz = byteSizeOf(((sqInt)(long)((((unsigned char *) address))) - 4));
	if (!(sz == 4)) {
		addr = primitiveFail();
		goto l1;
	}
	addr = ((((((unsigned char *) address))[3]) + (((((unsigned char *) address))[2]) << 8)) + (((((unsigned char *) address))[1]) << 16)) + (((((unsigned char *) address))[0]) << 24);
l1:	/* end netAddressToInt: */;
	/* begin socketValueOf: */
success((isBytes(socket))
	 && ((byteSizeOf(socket)) == (socketRecordSize())));
	s = (failed()
		? null
		: ((SocketPtr) (firstIndexableField(socket))));
	if (!(failed())) {
		sqSocketBindToPort(s, addr, port);
	}
	if (failed()) {
		return null;
	}
	pop(3);
	return null;
}

EXPORT(sqInt)
primitiveSocketCloseConnection(void)
{
	// SocketPlugin>>#primitiveSocketCloseConnection
	SocketPtr  s;
	sqInt socket;

	socket = stackValue(0);
	if (failed()) {
		return null;
	}
	/* begin socketValueOf: */
success((isBytes(socket))
	 && ((byteSizeOf(socket)) == (socketRecordSize())));
	s = (failed()
		? null
		: ((SocketPtr) (firstIndexableField(socket))));
	if (!(failed())) {
		sqSocketCloseConnection(s);
	}
	if (failed()) {
		return null;
	}
	pop(1);
	return null;
}

EXPORT(sqInt)
primitiveSocketConnectionStatus(void)
{
	// SocketPlugin>>#primitiveSocketConnectionStatus
	SocketPtr  s;
	sqInt socket;
	sqInt status;
	sqInt _return_value;

	socket = stackValue(0);
	if (failed()) {
		return null;
	}
	/* begin socketValueOf: */
success((isBytes(socket))
	 && ((byteSizeOf(socket)) == (socketRecordSize())));
	s = (failed()
		? null
		: ((SocketPtr) (firstIndexableField(socket))));
	if (!(failed())) {
		status = sqSocketConnectionStatus(s);
	}
	_return_value = integerObjectOf(status);
	if (failed()) {
		return null;
	}
	popthenPush(2, _return_value);
	return null;
}

EXPORT(sqInt)
primitiveSocketConnectTo(void)
{
	// SocketPlugin>>#primitiveSocketConnectTo
	char *addrBase;
	sqInt addrSize;
	SocketPtr s;
	sqInt socket;
	sqInt socketAddress;

	socket = stackValue(1);
	socketAddress = stackValue(0);
	if (failed()) {
		return null;
	}
	/* begin socketValueOf: */
success((isBytes(socket))
	 && ((byteSizeOf(socket)) == (socketRecordSize())));
	s = (failed()
		? null
		: ((SocketPtr) (firstIndexableField(socket))));
	addrSize = byteSizeOf(socketAddress);
	addrBase = ((char *) (firstIndexableField(socketAddress)));
	if (!(failed())) {
		sqSocketConnectToAddressSize(s, addrBase, addrSize);
	}
	if (failed()) {
		return null;
	}
	pop(2);
	return null;
}

EXPORT(sqInt)
primitiveSocketConnectToPort(void)
{
	// SocketPlugin>>#primitiveSocketConnectToPort
	sqInt addr;
	char *address;
	sqInt okToConnect;
	sqInt port;
	SocketPtr s;
	sqInt socket;
	sqInt sz;

	socket = stackValue(2);
	success(isBytes(stackValue(1)));
	address = ((char *) (firstIndexableField(stackValue(1))));
	port = stackIntegerValue(0);
	if (failed()) {
		return null;
	}
	/* begin netAddressToInt: */
sz = byteSizeOf(((sqInt)(long)((((unsigned char *) address))) - 4));
	if (!(sz == 4)) {
		addr = primitiveFail();
		goto l1;
	}
	addr = ((((((unsigned char *) address))[3]) + (((((unsigned char *) address))[2]) << 8)) + (((((unsigned char *) address))[1]) << 16)) + (((((unsigned char *) address))[0]) << 24);
l1:	/* end netAddressToInt: */;
	if (sCCTPfn != 0) {
okToConnect =  ((int (*) (int, int)) sCCTPfn)(addr, port);
		if (!okToConnect) {
primitiveFail();
			return null;
		}
	}
	/* begin socketValueOf: */
success((isBytes(socket))
	 && ((byteSizeOf(socket)) == (socketRecordSize())));
	s = (failed()
		? null
		: ((SocketPtr) (firstIndexableField(socket))));
	if (!(failed())) {
		sqSocketConnectToPort(s, addr, port);
	}
	if (failed()) {
		return null;
	}
	pop(3);
	return null;
}

EXPORT(sqInt)
primitiveSocketCreate(void)
{
	// SocketPlugin>>#primitiveSocketCreate
	sqInt netType;
	sqInt okToCreate;
	sqInt recvBufSize;
	SocketPtr  s;
	sqInt semaIndex;
	sqInt sendBufSize;
	sqInt socketOop;
	sqInt socketType;

	netType = stackIntegerValue(4);
	socketType = stackIntegerValue(3);
	recvBufSize = stackIntegerValue(2);
	sendBufSize = stackIntegerValue(1);
	semaIndex = stackIntegerValue(0);
	if (failed()) {
		return null;
	}
	if (sCCSOTfn != 0) {
okToCreate =  ((int (*) (int, int)) sCCSOTfn)(netType, socketType);
		if (!okToCreate) {
primitiveFail();
			return null;
		}
	}
	socketOop = instantiateClassindexableSize(classByteArray(), socketRecordSize());
	/* begin socketValueOf: */
success((isBytes(socketOop))
	 && ((byteSizeOf(socketOop)) == (socketRecordSize())));
	s = (failed()
		? null
		: ((SocketPtr) (firstIndexableField(socketOop))));
	sqSocketCreateNetTypeSocketTypeRecvBytesSendBytesSemaID(s, netType, socketType, recvBufSize, sendBufSize, semaIndex);
	if (failed()) {
		return null;
	}
	popthenPush(6, socketOop);
	return null;
}

EXPORT(sqInt)
primitiveSocketCreate3Semaphores(void)
{
	// SocketPlugin>>#primitiveSocketCreate3Semaphores
	sqInt aReadSema;
	sqInt aWriteSema;
	sqInt netType;
	sqInt okToCreate;
	sqInt recvBufSize;
	SocketPtr  s;
	sqInt semaIndex;
	sqInt sendBufSize;
	sqInt socketOop;
	sqInt socketType;

	netType = stackIntegerValue(6);
	socketType = stackIntegerValue(5);
	recvBufSize = stackIntegerValue(4);
	sendBufSize = stackIntegerValue(3);
	semaIndex = stackIntegerValue(2);
	aReadSema = stackIntegerValue(1);
	aWriteSema = stackIntegerValue(0);
	if (failed()) {
		return null;
	}
	if (sCCSOTfn != 0) {
okToCreate =  ((int (*) (int, int)) sCCSOTfn)(netType, socketType);
		if (!okToCreate) {
primitiveFail();
			return null;
		}
	}
	socketOop = instantiateClassindexableSize(classByteArray(), socketRecordSize());
	/* begin socketValueOf: */
success((isBytes(socketOop))
	 && ((byteSizeOf(socketOop)) == (socketRecordSize())));
	s = (failed()
		? null
		: ((SocketPtr) (firstIndexableField(socketOop))));
	sqSocketCreateNetTypeSocketTypeRecvBytesSendBytesSemaIDReadSemaIDWriteSemaID(s, netType, socketType, recvBufSize, sendBufSize, semaIndex, aReadSema, aWriteSema);
	if (failed()) {
		return null;
	}
	popthenPush(8, socketOop);
	return null;
}

EXPORT(sqInt)
primitiveSocketDestroy(void)
{
	// SocketPlugin>>#primitiveSocketDestroy
	SocketPtr s;
	sqInt socket;

	socket = stackValue(0);
	if (failed()) {
		return null;
	}
	/* begin socketValueOf: */
success((isBytes(socket))
	 && ((byteSizeOf(socket)) == (socketRecordSize())));
	s = (failed()
		? null
		: ((SocketPtr) (firstIndexableField(socket))));
	if (!(failed())) {
		sqSocketDestroy(s);
	}
	if (failed()) {
		return null;
	}
	pop(1);
	return null;
}

EXPORT(sqInt)
primitiveSocketError(void)
{
	// SocketPlugin>>#primitiveSocketError
	sqInt err;
	SocketPtr  s;
	sqInt socket;
	sqInt _return_value;

	socket = stackValue(0);
	if (failed()) {
		return null;
	}
	/* begin socketValueOf: */
success((isBytes(socket))
	 && ((byteSizeOf(socket)) == (socketRecordSize())));
	s = (failed()
		? null
		: ((SocketPtr) (firstIndexableField(socket))));
	if (!(failed())) {
		err = sqSocketError(s);
	}
	_return_value = integerObjectOf(err);
	if (failed()) {
		return null;
	}
	popthenPush(2, _return_value);
	return null;
}

EXPORT(sqInt)
primitiveSocketGetOptions(void)
{
	// SocketPlugin>>#primitiveSocketGetOptions
	sqInt errorCode;
	sqInt optionName;
	sqInt optionNameSize;
	char *optionNameStart;
	sqInt results;
	sqInt returnedValue;
	SocketPtr s;
	sqInt socket;

	socket = stackValue(1);
	optionName = stackValue(0);
	if (failed()) {
		return null;
	}
	/* begin socketValueOf: */
success((isBytes(socket))
	 && ((byteSizeOf(socket)) == (socketRecordSize())));
	s = (failed()
		? null
		: ((SocketPtr) (firstIndexableField(socket))));
	success(isBytes(optionName));
	optionNameStart = ((char *) (firstIndexableField(optionName)));
	optionNameSize = slotSizeOf(optionName);
	if (failed()) {
		return null;
	}
	returnedValue = 0;
	errorCode = sqSocketGetOptionsoptionNameStartoptionNameSizereturnedValue(s, optionNameStart, optionNameSize, (&returnedValue));
	results = instantiateClassindexableSize(classArray(), 2);
	storePointerofObjectwithValue(0, results, integerObjectOf(errorCode));
	storePointerofObjectwithValue(1, results, integerObjectOf(returnedValue));
	if (failed()) {
		return null;
	}
	popthenPush(3, results);
	return null;
}


/*	one part of the wierdass dual prim primitiveSocketListenOnPort which 
	was warped by some demented evil person determined to twist the very 
	nature of reality */

EXPORT(sqInt)
primitiveSocketListenOnPort(void)
{
	// SocketPlugin>>#primitiveSocketListenOnPort
	sqInt okToListen;
	sqInt port;
	SocketPtr  s;
	sqInt socket;

	socket = stackValue(1);
	port = stackIntegerValue(0);
	if (failed()) {
		return null;
	}
	/* begin socketValueOf: */
success((isBytes(socket))
	 && ((byteSizeOf(socket)) == (socketRecordSize())));
	s = (failed()
		? null
		: ((SocketPtr) (firstIndexableField(socket))));
	if (sCCLOPfn != 0) {
okToListen =  ((int (*) (SocketPtr, int)) sCCLOPfn)(s, port);
		if (!okToListen) {
primitiveFail();
			return null;
		}
	}
	if (!(failed())) {
		sqSocketListenOnPort(s, port);
	}
	if (failed()) {
		return null;
	}
	pop(2);
	return null;
}


/*	second part of the wierdass dual prim primitiveSocketListenOnPort 
	which was warped by some demented evil person determined to twist the 
	very nature of reality */

EXPORT(sqInt)
primitiveSocketListenOnPortBacklog(void)
{
	// SocketPlugin>>#primitiveSocketListenOnPortBacklog
	sqInt backlog;
	sqInt okToListen;
	sqInt port;
	SocketPtr s;
	sqInt socket;

	socket = stackValue(2);
	port = stackIntegerValue(1);
	backlog = stackIntegerValue(0);
	if (failed()) {
		return null;
	}
	/* begin socketValueOf: */
success((isBytes(socket))
	 && ((byteSizeOf(socket)) == (socketRecordSize())));
	s = (failed()
		? null
		: ((SocketPtr) (firstIndexableField(socket))));
	if (sCCLOPfn != 0) {
okToListen =  ((int (*) (SocketPtr, int)) sCCLOPfn)(s, port);
		if (!okToListen) {
primitiveFail();
			return null;
		}
	}
	sqSocketListenOnPortBacklogSize(s, port, backlog);
	if (failed()) {
		return null;
	}
	pop(3);
	return null;
}


/*	Bind a socket to the given port and interface address with no more than
	backlog pending connections. The socket can be UDP, in which case the
	backlog should be specified as zero.
 */

EXPORT(sqInt)
primitiveSocketListenOnPortBacklogInterface(void)
{
	// SocketPlugin>>#primitiveSocketListenOnPortBacklogInterface
	sqInt addr;
	sqInt backlog;
	char *ifAddr;
	sqInt okToListen;
	sqInt port;
	SocketPtr s;
	sqInt socket;
	sqInt sz;

	socket = stackValue(3);
	port = stackIntegerValue(2);
	backlog = stackIntegerValue(1);
	success(isBytes(stackValue(0)));
	ifAddr = ((char *) (firstIndexableField(stackValue(0))));
	if (failed()) {
		return null;
	}
	/* begin socketValueOf: */
success((isBytes(socket))
	 && ((byteSizeOf(socket)) == (socketRecordSize())));
	s = (failed()
		? null
		: ((SocketPtr) (firstIndexableField(socket))));
	if (sCCLOPfn != 0) {
okToListen =  ((int (*) (SocketPtr, int)) sCCLOPfn)(s, port);
		if (!okToListen) {
primitiveFail();
			return null;
		}
	}
	/* begin netAddressToInt: */
sz = byteSizeOf(((sqInt)(long)((((unsigned char *) ifAddr))) - 4));
	if (!(sz == 4)) {
		addr = primitiveFail();
		goto l1;
	}
	addr = ((((((unsigned char *) ifAddr))[3]) + (((((unsigned char *) ifAddr))[2]) << 8)) + (((((unsigned char *) ifAddr))[1]) << 16)) + (((((unsigned char *) ifAddr))[0]) << 24);
l1:	/* end netAddressToInt: */;
	sqSocketListenOnPortBacklogSizeInterface(s, port, backlog, addr);
	if (failed()) {
		return null;
	}
	pop(4);
	return null;
}

EXPORT(sqInt)
primitiveSocketListenWithBacklog(void)
{
	// SocketPlugin>>#primitiveSocketListenWithBacklog
	sqInt backlogSize;
	SocketPtr s;
	sqInt socket;

	socket = stackValue(1);
	backlogSize = stackIntegerValue(0);
	if (failed()) {
		return null;
	}
	/* begin socketValueOf: */
success((isBytes(socket))
	 && ((byteSizeOf(socket)) == (socketRecordSize())));
	s = (failed()
		? null
		: ((SocketPtr) (firstIndexableField(socket))));
	if (!(failed())) {
		sqSocketListenBacklog(s, backlogSize);
	}
	if (failed()) {
		return null;
	}
	pop(2);
	return null;
}


/*	Backward compatibility */

EXPORT(sqInt)
primitiveSocketListenWithOrWithoutBacklog(void)
{
	// SocketPlugin>>#primitiveSocketListenWithOrWithoutBacklog
	if ((methodArgumentCount()) == 2) {
		return primitiveSocketListenOnPort();
	}
	else {
return primitiveSocketListenOnPortBacklog();
	}
}

EXPORT(sqInt)
primitiveSocketLocalAddress(void)
{
	// SocketPlugin>>#primitiveSocketLocalAddress
	sqInt addr;
	SocketPtr s;
	sqInt socket;
	sqInt _return_value;

	socket = stackValue(0);
	if (failed()) {
		return null;
	}
	/* begin socketValueOf: */
success((isBytes(socket))
	 && ((byteSizeOf(socket)) == (socketRecordSize())));
	s = (failed()
		? null
		: ((SocketPtr) (firstIndexableField(socket))));
	addr = sqSocketLocalAddress(s);
	_return_value = intToNetAddress(addr);
	if (failed()) {
		return null;
	}
	popthenPush(2, _return_value);
	return null;
}

EXPORT(sqInt)
primitiveSocketLocalAddressResult(void)
{
	// SocketPlugin>>#primitiveSocketLocalAddressResult
	char *addrBase;
	sqInt addrSize;
	SocketPtr s;
	sqInt socket;
	sqInt socketAddress;

	socket = stackValue(1);
	socketAddress = stackValue(0);
	if (failed()) {
		return null;
	}
	/* begin socketValueOf: */
success((isBytes(socket))
	 && ((byteSizeOf(socket)) == (socketRecordSize())));
	s = (failed()
		? null
		: ((SocketPtr) (firstIndexableField(socket))));
	addrSize = byteSizeOf(socketAddress);
	addrBase = ((char *) (firstIndexableField(socketAddress)));
	if (!(failed())) {
		sqSocketLocalAddressResultSize(s, addrBase, addrSize);
	}
	if (failed()) {
		return null;
	}
	pop(2);
	return null;
}

EXPORT(sqInt)
primitiveSocketLocalAddressSize(void)
{
	// SocketPlugin>>#primitiveSocketLocalAddressSize
	SocketPtr s;
	sqInt size;
	sqInt socket;
	sqInt _return_value;

	socket = stackValue(0);
	if (failed()) {
		return null;
	}
	/* begin socketValueOf: */
success((isBytes(socket))
	 && ((byteSizeOf(socket)) == (socketRecordSize())));
	s = (failed()
		? null
		: ((SocketPtr) (firstIndexableField(socket))));
	if (failed()) {
		return null;
	}
	size = sqSocketLocalAddressSize(s);
	if (failed()) {
		return null;
	}
	_return_value = integerObjectOf(size);
	if (failed()) {
		return null;
	}
	popthenPush(2, _return_value);
	return null;
}

EXPORT(sqInt)
primitiveSocketLocalPort(void)
{
	// SocketPlugin>>#primitiveSocketLocalPort
	sqInt port;
	SocketPtr  s;
	sqInt socket;
	sqInt _return_value;

	socket = stackValue(0);
	if (failed()) {
		return null;
	}
	/* begin socketValueOf: */
success((isBytes(socket))
	 && ((byteSizeOf(socket)) == (socketRecordSize())));
	s = (failed()
		? null
		: ((SocketPtr) (firstIndexableField(socket))));
	port = sqSocketLocalPort(s);
	_return_value = integerObjectOf(port);
	if (failed()) {
		return null;
	}
	popthenPush(2, _return_value);
	return null;
}

EXPORT(sqInt)
primitiveSocketReceiveDataAvailable(void)
{
	// SocketPlugin>>#primitiveSocketReceiveDataAvailable
	sqInt dataIsAvailable;
	SocketPtr s;
	sqInt socket;
	sqInt _return_value;

	socket = stackValue(0);
	if (failed()) {
		return null;
	}
	/* begin socketValueOf: */
success((isBytes(socket))
	 && ((byteSizeOf(socket)) == (socketRecordSize())));
	s = (failed()
		? null
		: ((SocketPtr) (firstIndexableField(socket))));
	dataIsAvailable = sqSocketReceiveDataAvailable(s);
	_return_value = ((dataIsAvailable) ? trueObject() : falseObject());
	if (failed()) {
		return null;
	}
	popthenPush(2, _return_value);
	return null;
}

EXPORT(sqInt)
primitiveSocketReceiveDataBufCount(void)
{
	// SocketPlugin>>#primitiveSocketReceiveDataBufCount
	sqInt array;
	char *arrayBase;
	char *bufStart;
	sqInt byteSize;
	sqInt bytesReceived;
	sqInt count;
	SocketPtr s;
	sqInt socket;
	sqInt startIndex;
	sqInt _return_value;

	socket = stackValue(3);
	array = stackValue(2);
	startIndex = stackIntegerValue(1);
	count = stackIntegerValue(0);
	if (failed()) {
		return null;
	}
	/* begin socketValueOf: */
success((isBytes(socket))
	 && ((byteSizeOf(socket)) == (socketRecordSize())));
	s = (failed()
		? null
		: ((SocketPtr) (firstIndexableField(socket))));
	success(isWordsOrBytes(array));
	if (isWords(array)) {
		byteSize = 4;
	}
	else {
byteSize = 1;
	}
	success((startIndex >= 1)
	 && ((count >= 0)
	 && (((startIndex + count) - 1) <= (slotSizeOf(array)))));
	if (!(failed())) {

		/* Note: adjust bufStart for zero-origin indexing */


		/* Note: adjust bufStart for zero-origin indexing */

arrayBase = ((char *) (firstIndexableField(array)));
		bufStart = arrayBase + ((startIndex - 1) * byteSize);
		bytesReceived = sqSocketReceiveDataBufCount(s, bufStart, count * byteSize);
	}
	_return_value = integerObjectOf((bytesReceived / byteSize));
	if (failed()) {
		return null;
	}
	popthenPush(5, _return_value);
	return null;
}

EXPORT(sqInt)
primitiveSocketReceiveUDPDataBufCount(void)
{
	// SocketPlugin>>#primitiveSocketReceiveUDPDataBufCount
	sqInt address;
	sqInt array;
	char *arrayBase;
	char *bufStart;
	sqInt bytesReceived;
	sqInt count;
	sqInt elementSize;
	sqInt moreFlag;
	sqInt port;
	sqInt results;
	SocketPtr s;
	sqInt socket;
	sqInt startIndex;

	socket = stackValue(3);
	array = stackValue(2);
	startIndex = stackIntegerValue(1);
	count = stackIntegerValue(0);
	if (failed()) {
		return null;
	}
	/* begin socketValueOf: */
success((isBytes(socket))
	 && ((byteSizeOf(socket)) == (socketRecordSize())));
	s = (failed()
		? null
		: ((SocketPtr) (firstIndexableField(socket))));
	success(isWordsOrBytes(array));
	if (isWords(array)) {
		elementSize = 4;
	}
	else {
elementSize = 1;
	}
	success((startIndex >= 1)
	 && ((count >= 0)
	 && (((startIndex + count) - 1) <= (slotSizeOf(array)))));
	if (!(failed())) {

		/* Note: adjust bufStart for zero-origin indexing */


		/* Note: adjust bufStart for zero-origin indexing */

arrayBase = ((char *) (firstIndexableField(array)));
		bufStart = arrayBase + ((startIndex - 1) * elementSize);
		address = 0;
		port = 0;
		moreFlag = 0;

		/* allocate storage for results, remapping newly allocated
		   oops in case GC happens during allocation */

		bytesReceived = sqSocketReceiveUDPDataBufCountaddressportmoreFlag(s, bufStart, count * elementSize, (&address), (&port), (&moreFlag));
		pushRemappableOop(intToNetAddress(address));
		results = instantiateClassindexableSize(classArray(), 4);
		storePointerofObjectwithValue(0, results, integerObjectOf((bytesReceived / elementSize)));
		storePointerofObjectwithValue(1, results, popRemappableOop());
		storePointerofObjectwithValue(2, results, integerObjectOf(port));
		storePointerofObjectwithValue(3, results, (moreFlag
			? trueObject()
			: falseObject()));
	}
	if (failed()) {
		return null;
	}
	popthenPush(5, results);
	return null;
}

EXPORT(sqInt)
primitiveSocketRemoteAddress(void)
{
	// SocketPlugin>>#primitiveSocketRemoteAddress
	sqInt addr;
	SocketPtr s;
	sqInt socket;
	sqInt _return_value;

	socket = stackValue(0);
	if (failed()) {
		return null;
	}
	/* begin socketValueOf: */
success((isBytes(socket))
	 && ((byteSizeOf(socket)) == (socketRecordSize())));
	s = (failed()
		? null
		: ((SocketPtr) (firstIndexableField(socket))));
	addr = sqSocketRemoteAddress(s);
	_return_value = intToNetAddress(addr);
	if (failed()) {
		return null;
	}
	popthenPush(2, _return_value);
	return null;
}

EXPORT(sqInt)
primitiveSocketRemoteAddressResult(void)
{
	// SocketPlugin>>#primitiveSocketRemoteAddressResult
	char *addrBase;
	sqInt addrSize;
	SocketPtr s;
	sqInt socket;
	sqInt socketAddress;

	socket = stackValue(1);
	socketAddress = stackValue(0);
	if (failed()) {
		return null;
	}
	/* begin socketValueOf: */
success((isBytes(socket))
	 && ((byteSizeOf(socket)) == (socketRecordSize())));
	s = (failed()
		? null
		: ((SocketPtr) (firstIndexableField(socket))));
	addrSize = byteSizeOf(socketAddress);
	addrBase = ((char *) (firstIndexableField(socketAddress)));
	if (!(failed())) {
		sqSocketRemoteAddressResultSize(s, addrBase, addrSize);
	}
	if (failed()) {
		return null;
	}
	pop(2);
	return null;
}

EXPORT(sqInt)
primitiveSocketRemoteAddressSize(void)
{
	// SocketPlugin>>#primitiveSocketRemoteAddressSize
	SocketPtr s;
	sqInt size;
	sqInt socket;
	sqInt _return_value;

	socket = stackValue(0);
	if (failed()) {
		return null;
	}
	/* begin socketValueOf: */
success((isBytes(socket))
	 && ((byteSizeOf(socket)) == (socketRecordSize())));
	s = (failed()
		? null
		: ((SocketPtr) (firstIndexableField(socket))));
	if (failed()) {
		return null;
	}
	size = sqSocketRemoteAddressSize(s);
	if (failed()) {
		return null;
	}
	_return_value = integerObjectOf(size);
	if (failed()) {
		return null;
	}
	popthenPush(2, _return_value);
	return null;
}

EXPORT(sqInt)
primitiveSocketRemotePort(void)
{
	// SocketPlugin>>#primitiveSocketRemotePort
	sqInt port;
	SocketPtr s;
	sqInt socket;
	sqInt _return_value;

	socket = stackValue(0);
	if (failed()) {
		return null;
	}
	/* begin socketValueOf: */
success((isBytes(socket))
	 && ((byteSizeOf(socket)) == (socketRecordSize())));
	s = (failed()
		? null
		: ((SocketPtr) (firstIndexableField(socket))));
	port = sqSocketRemotePort(s);
	_return_value = integerObjectOf(port);
	if (failed()) {
		return null;
	}
	popthenPush(2, _return_value);
	return null;
}

EXPORT(sqInt)
primitiveSocketSCTPEnableDataIOEvent(void)
{
	// SocketPlugin>>#primitiveSocketSCTPEnableDataIOEvent
	sqInt aFlag;
	sqInt done;
	SocketPtr s;
	sqInt socket;
	sqInt _return_value;

	socket = stackValue(1);
	aFlag = stackIntegerValue(0);
	if (failed()) {
		return null;
	}
	/* begin socketValueOf: */
success((isBytes(socket))
	 && ((byteSizeOf(socket)) == (socketRecordSize())));
	s = (failed()
		? null
		: ((SocketPtr) (firstIndexableField(socket))));
	done = sqSocketSCTPEnableDataIOEventenable(s, aFlag);
	_return_value = ((done) ? trueObject() : falseObject());
	if (failed()) {
		return null;
	}
	popthenPush(3, _return_value);
	return null;
}

EXPORT(sqInt)
primitiveSocketSCTPReceive(void)
{
	// SocketPlugin>>#primitiveSocketSCTPReceive
	sqInt address;
	sqInt array;
	char *arrayBase;
	sqInt assoc;
	char *bufStart;
	sqInt byteSize;
	sqInt bytesReceived;
	sqInt count;
	sqInt port;
	sqInt ppid;
	sqInt results;
	SocketPtr s;
	sqInt socket;
	sqInt ssn;
	sqInt startIndex;
	sqInt stream;

	socket = stackValue(3);
	array = stackValue(2);
	startIndex = stackIntegerValue(1);
	count = stackIntegerValue(0);
	if (failed()) {
		return null;
	}
	/* begin socketValueOf: */
success((isBytes(socket))
	 && ((byteSizeOf(socket)) == (socketRecordSize())));
	s = (failed()
		? null
		: ((SocketPtr) (firstIndexableField(socket))));
	success(isWordsOrBytes(array));
	if (isWords(array)) {
		byteSize = 4;
	}
	else {
byteSize = 1;
	}
	success((startIndex >= 1)
	 && ((count >= 0)
	 && (((startIndex + count) - 1) <= (slotSizeOf(array)))));
	if (!(failed())) {

		/* Note: adjust bufStart for zero-origin indexing */


		/* Note: adjust bufStart for zero-origin indexing */

arrayBase = ((char *) (firstIndexableField(array)));

		/* allocate storage for results, remapping newly allocated
		   oops in case GC happens during allocation */

		bufStart = arrayBase + ((startIndex - 1) * byteSize);
		address = 0;
		port = 0;
		ssn = 0;
		stream = 0;
		ppid = 0;
		assoc = 0;
		bytesReceived = sqSocketSCTPReceiveCountAddressPortStreamAssocIdPpidSsn(s, bufStart, count * byteSize, &address, &port, &stream, &assoc, &ppid, &ssn);
		pushRemappableOop(integerObjectOf(ssn));
		pushRemappableOop(integerObjectOf(ppid));
		pushRemappableOop(integerObjectOf(assoc));
		pushRemappableOop(integerObjectOf(stream));
		pushRemappableOop(integerObjectOf(port));
		pushRemappableOop(intToNetAddress(address));
		pushRemappableOop(integerObjectOf((bytesReceived / byteSize)));
		pushRemappableOop(instantiateClassindexableSize(classArray(), 7));
		results = popRemappableOop();
		storePointerofObjectwithValue(0, results, popRemappableOop());
		storePointerofObjectwithValue(1, results, popRemappableOop());
		storePointerofObjectwithValue(2, results, popRemappableOop());
		storePointerofObjectwithValue(3, results, popRemappableOop());
		storePointerofObjectwithValue(4, results, popRemappableOop());
		storePointerofObjectwithValue(5, results, popRemappableOop());
		storePointerofObjectwithValue(6, results, popRemappableOop());
	}
	if (failed()) {
		return null;
	}
	popthenPush(5, results);
	return null;
}


/*	It is a pain to wrap the sctp_sndrcvinfo structure. So right now we only
	export the parameters we need and leave the others unused. */

EXPORT(sqInt)
primitiveSocketSCTPSend(void)
{
	// SocketPlugin>>#primitiveSocketSCTPSend
	sqInt aPpid;
	sqInt array;
	char *arrayBase;
	sqInt aStream;
	sqInt assocId;
	char *bufStart;
	sqInt byteSize;
	sqInt bytesSent;
	sqInt count;
	SocketPtr s;
	sqInt socket;
	sqInt startIndex;
	sqInt _return_value;

	socket = stackValue(6);
	array = stackValue(5);
	startIndex = stackIntegerValue(4);
	count = stackIntegerValue(3);
	aStream = stackIntegerValue(2);
	assocId = stackIntegerValue(1);
	aPpid = stackIntegerValue(0);
	if (failed()) {
		return null;
	}
	/* begin socketValueOf: */
success((isBytes(socket))
	 && ((byteSizeOf(socket)) == (socketRecordSize())));
	s = (failed()
		? null
		: ((SocketPtr) (firstIndexableField(socket))));
	success(isWordsOrBytes(array));
	if (isWords(array)) {
		byteSize = 4;
	}
	else {
byteSize = 1;
	}
	success((startIndex >= 1)
	 && ((count >= 0)
	 && (((startIndex + count) - 1) <= (slotSizeOf(array)))));
	if (!(failed())) {

		/* Note: adjust bufStart for zero-origin indexing */


		/* Note: adjust bufStart for zero-origin indexing */

arrayBase = ((char *) (firstIndexableField(array)));
		bufStart = arrayBase + ((startIndex - 1) * byteSize);
		bytesSent = sqSocketSCTPSendSendDataBufCountStreamAssocIdPpid(s, bufStart, count * byteSize, aStream, assocId, aPpid);
	}
	_return_value = integerObjectOf((bytesSent / byteSize));
	if (failed()) {
		return null;
	}
	popthenPush(8, _return_value);
	return null;
}

EXPORT(sqInt)
primitiveSocketSendDataBufCount(void)
{
	// SocketPlugin>>#primitiveSocketSendDataBufCount
	sqInt array;
	char *arrayBase;
	char *bufStart;
	sqInt byteSize;
	sqInt bytesSent;
	sqInt count;
	SocketPtr s;
	sqInt socket;
	sqInt startIndex;
	sqInt _return_value;

	socket = stackValue(3);
	array = stackValue(2);
	startIndex = stackIntegerValue(1);
	count = stackIntegerValue(0);
	if (failed()) {
		return null;
	}
	/* begin socketValueOf: */
success((isBytes(socket))
	 && ((byteSizeOf(socket)) == (socketRecordSize())));
	s = (failed()
		? null
		: ((SocketPtr) (firstIndexableField(socket))));
	success(isWordsOrBytes(array));
	if (isWords(array)) {
		byteSize = 4;
	}
	else {
byteSize = 1;
	}
	success((startIndex >= 1)
	 && ((count >= 0)
	 && (((startIndex + count) - 1) <= (slotSizeOf(array)))));
	if (!(failed())) {

		/* Note: adjust bufStart for zero-origin indexing */


		/* Note: adjust bufStart for zero-origin indexing */

arrayBase = ((char *) (firstIndexableField(array)));
		bufStart = arrayBase + ((startIndex - 1) * byteSize);
		bytesSent = sqSocketSendDataBufCount(s, bufStart, count * byteSize);
	}
	_return_value = integerObjectOf((bytesSent / byteSize));
	if (failed()) {
		return null;
	}
	popthenPush(5, _return_value);
	return null;
}

EXPORT(sqInt)
primitiveSocketSendDone(void)
{
	// SocketPlugin>>#primitiveSocketSendDone
	sqInt done;
	SocketPtr s;
	sqInt socket;
	sqInt _return_value;

	socket = stackValue(0);
	if (failed()) {
		return null;
	}
	/* begin socketValueOf: */
success((isBytes(socket))
	 && ((byteSizeOf(socket)) == (socketRecordSize())));
	s = (failed()
		? null
		: ((SocketPtr) (firstIndexableField(socket))));
	done = sqSocketSendDone(s);
	_return_value = ((done) ? trueObject() : falseObject());
	if (failed()) {
		return null;
	}
	popthenPush(2, _return_value);
	return null;
}

EXPORT(sqInt)
primitiveSocketSendUDPDataBufCount(void)
{
	// SocketPlugin>>#primitiveSocketSendUDPDataBufCount
	sqInt address;
	sqInt array;
	char *arrayBase;
	char *bufStart;
	sqInt byteSize;
	sqInt bytesSent;
	sqInt count;
	char *hostAddress;
	sqInt portNumber;
	SocketPtr s;
	sqInt socket;
	sqInt startIndex;
	sqInt sz;
	sqInt _return_value;

	socket = stackValue(5);
	array = stackValue(4);
	success(isBytes(stackValue(3)));
	hostAddress = ((char *) (firstIndexableField(stackValue(3))));
	portNumber = stackIntegerValue(2);
	startIndex = stackIntegerValue(1);
	count = stackIntegerValue(0);
	if (failed()) {
		return null;
	}
	/* begin socketValueOf: */
success((isBytes(socket))
	 && ((byteSizeOf(socket)) == (socketRecordSize())));
	s = (failed()
		? null
		: ((SocketPtr) (firstIndexableField(socket))));
	success(isWordsOrBytes(array));
	if (isWords(array)) {
		byteSize = 4;
	}
	else {
byteSize = 1;
	}
	success((startIndex >= 1)
	 && ((count >= 0)
	 && (((startIndex + count) - 1) <= (slotSizeOf(array)))));
	if (!(failed())) {

		/* Note: adjust bufStart for zero-origin indexing */


		/* Note: adjust bufStart for zero-origin indexing */

arrayBase = ((char *) (firstIndexableField(array)));
		bufStart = arrayBase + ((startIndex - 1) * byteSize);
		/* begin netAddressToInt: */
sz = byteSizeOf(((sqInt)(long)((((unsigned char *) hostAddress))) - 4));
		if (!(sz == 4)) {
			address = primitiveFail();
			goto l1;
		}
		address = ((((((unsigned char *) hostAddress))[3]) + (((((unsigned char *) hostAddress))[2]) << 8)) + (((((unsigned char *) hostAddress))[1]) << 16)) + (((((unsigned char *) hostAddress))[0]) << 24);
	l1:	/* end netAddressToInt: */;
		bytesSent = sqSockettoHostportSendDataBufCount(s, address, portNumber, bufStart, count * byteSize);
	}
	_return_value = integerObjectOf((bytesSent / byteSize));
	if (failed()) {
		return null;
	}
	popthenPush(7, _return_value);
	return null;
}


/*	THIS BADLY NEEDS TO BE REWRITTEN TO TAKE Booleans AND Integers AS WELL AS
	(OR INSTEAD OF) Strings.
	It is only used with booleans and integers and parsing these back out of
	strings in

	sqSocketSetOptions:optionNameStart:optionNameSize:optionValueStart:optionValueSize:returnedValue:
	is STUPID. */

EXPORT(sqInt)
primitiveSocketSetOptions(void)
{
	// SocketPlugin>>#primitiveSocketSetOptions
	sqInt errorCode;
	sqInt optionName;
	sqInt optionNameSize;
	char *optionNameStart;
	sqInt optionValue;
	sqInt optionValueSize;
	char *optionValueStart;
	sqInt results;
	sqInt returnedValue;
	SocketPtr s;
	sqInt socket;

	socket = stackValue(2);
	optionName = stackValue(1);
	optionValue = stackValue(0);
	if (failed()) {
		return null;
	}
	/* begin socketValueOf: */
success((isBytes(socket))
	 && ((byteSizeOf(socket)) == (socketRecordSize())));
	s = (failed()
		? null
		: ((SocketPtr) (firstIndexableField(socket))));
	success(isBytes(optionName));
	optionNameStart = ((char *) (firstIndexableField(optionName)));
	optionNameSize = slotSizeOf(optionName);
	success(isBytes(optionValue));
	optionValueStart = ((char *) (firstIndexableField(optionValue)));
	optionValueSize = slotSizeOf(optionValue);
	if (failed()) {
		return null;
	}
	returnedValue = 0;
	errorCode = sqSocketSetOptionsoptionNameStartoptionNameSizeoptionValueStartoptionValueSizereturnedValue(s, optionNameStart, optionNameSize, optionValueStart, optionValueSize, (&returnedValue));
	results = instantiateClassindexableSize(classArray(), 2);
	storePointerofObjectwithValue(0, results, integerObjectOf(errorCode));
	storePointerofObjectwithValue(1, results, integerObjectOf(returnedValue));
	if (failed()) {
		return null;
	}
	popthenPush(4, results);
	return null;
}


/*	Note: This is coded so that it can be run in Squeak. */

EXPORT(sqInt)
setInterpreter(struct VirtualMachine*anInterpreter)
{
	// InterpreterPlugin>>#setInterpreter:
	sqInt ok;

	interpreterProxy = anInterpreter;
	ok = ((interpreterProxy->majorVersion()) == (VM_PROXY_MAJOR))
	 && ((interpreterProxy->minorVersion()) >= (VM_PROXY_MINOR));
	if (ok) {

#if !defined(SQUEAK_BUILTIN_PLUGIN)
		byteSizeOf = interpreterProxy->byteSizeOf;
		classArray = interpreterProxy->classArray;
		classByteArray = interpreterProxy->classByteArray;
		classString = interpreterProxy->classString;
		failed = interpreterProxy->failed;
		falseObject = interpreterProxy->falseObject;
		firstIndexableField = interpreterProxy->firstIndexableField;
		instantiateClassindexableSize = interpreterProxy->instantiateClassindexableSize;
		integerObjectOf = interpreterProxy->integerObjectOf;
		ioLoadFunctionFrom = interpreterProxy->ioLoadFunctionFrom;
		isBytes = interpreterProxy->isBytes;
		isWords = interpreterProxy->isWords;
		isWordsOrBytes = interpreterProxy->isWordsOrBytes;
		methodArgumentCount = interpreterProxy->methodArgumentCount;
		pop = interpreterProxy->pop;
		popthenPush = interpreterProxy->popthenPush;
		popRemappableOop = interpreterProxy->popRemappableOop;
		primitiveFail = interpreterProxy->primitiveFail;
		pushBool = interpreterProxy->pushBool;
		pushRemappableOop = interpreterProxy->pushRemappableOop;
		slotSizeOf = interpreterProxy->slotSizeOf;
		stackIntegerValue = interpreterProxy->stackIntegerValue;
		stackValue = interpreterProxy->stackValue;
		storePointerofObjectwithValue = interpreterProxy->storePointerofObjectwithValue;
		success = interpreterProxy->success;
		trueObject = interpreterProxy->trueObject;
#endif /* !defined(SQUEAK_BUILTIN_PLUGIN) */
	}
	return ok;
}

EXPORT(sqInt)
shutdownModule(void)
{
	// SocketPlugin>>#shutdownModule
	return socketShutdown();
}


/*	Return the size of a Smalltalk socket record in bytes. */

static sqInt
socketRecordSize(void)
{
	// SocketPlugin>>#socketRecordSize
	return sizeof(SQSocket);
}


/*	We can not include netinet/sctp.h directly so we need to go via a
	primitive 
 */

static sqInt
socketSCTPSndRcvInfoSize(void)
{
	// SocketPlugin>>#socketSCTPSndRcvInfoSize
	return sqSocketSCTPSndRcvInfoSize();
}


/*	Return a pointer to the first byte of of the socket record within the 
	given Smalltalk object, or nil if socketOop is not a socket record. */

static SocketPtr
socketValueOf(sqInt socketOop)
{
	// SocketPlugin>>#socketValueOf:
	success((isBytes(socketOop))
	 && ((byteSizeOf(socketOop)) == (socketRecordSize())));
	return (failed()
		? null
		: ((SocketPtr) (firstIndexableField(socketOop))));
}

static void
sqAssert(sqInt aBool)
{
	// SmartSyntaxInterpreterPlugin>>#sqAssert:
	/* missing DebugCode */;
}


#ifdef SQUEAK_BUILTIN_PLUGIN

void* SocketPlugin_exports[][3] = {
	{"SocketPlugin", "getModuleName", (void*)getModuleName},
	{"SocketPlugin", "initialiseModule", (void*)initialiseModule},
	{"SocketPlugin", "moduleUnloaded", (void*)moduleUnloaded},
	{"SocketPlugin", "primitiveDisableSocketAccess", (void*)primitiveDisableSocketAccess},
	{"SocketPlugin", "primitiveHasSocketAccess", (void*)primitiveHasSocketAccess},
	{"SocketPlugin", "primitiveInitializeNetwork", (void*)primitiveInitializeNetwork},
	{"SocketPlugin", "primitiveResolverAbortLookup", (void*)primitiveResolverAbortLookup},
	{"SocketPlugin", "primitiveResolverAddressLookupResult", (void*)primitiveResolverAddressLookupResult},
	{"SocketPlugin", "primitiveResolverError", (void*)primitiveResolverError},
	{"SocketPlugin", "primitiveResolverGetAddressInfo", (void*)primitiveResolverGetAddressInfo},
	{"SocketPlugin", "primitiveResolverGetAddressInfoFamily", (void*)primitiveResolverGetAddressInfoFamily},
	{"SocketPlugin", "primitiveResolverGetAddressInfoNext", (void*)primitiveResolverGetAddressInfoNext},
	{"SocketPlugin", "primitiveResolverGetAddressInfoProtocol", (void*)primitiveResolverGetAddressInfoProtocol},
	{"SocketPlugin", "primitiveResolverGetAddressInfoResult", (void*)primitiveResolverGetAddressInfoResult},
	{"SocketPlugin", "primitiveResolverGetAddressInfoSize", (void*)primitiveResolverGetAddressInfoSize},
	{"SocketPlugin", "primitiveResolverGetAddressInfoType", (void*)primitiveResolverGetAddressInfoType},
	{"SocketPlugin", "primitiveResolverGetNameInfo", (void*)primitiveResolverGetNameInfo},
	{"SocketPlugin", "primitiveResolverGetNameInfoHostResult", (void*)primitiveResolverGetNameInfoHostResult},
	{"SocketPlugin", "primitiveResolverGetNameInfoHostSize", (void*)primitiveResolverGetNameInfoHostSize},
	{"SocketPlugin", "primitiveResolverGetNameInfoServiceResult", (void*)primitiveResolverGetNameInfoServiceResult},
	{"SocketPlugin", "primitiveResolverGetNameInfoServiceSize", (void*)primitiveResolverGetNameInfoServiceSize},
	{"SocketPlugin", "primitiveResolverHostNameResult", (void*)primitiveResolverHostNameResult},
	{"SocketPlugin", "primitiveResolverHostNameSize", (void*)primitiveResolverHostNameSize},
	{"SocketPlugin", "primitiveResolverLocalAddress", (void*)primitiveResolverLocalAddress},
	{"SocketPlugin", "primitiveResolverNameLookupResult", (void*)primitiveResolverNameLookupResult},
	{"SocketPlugin", "primitiveResolverStartAddressLookup", (void*)primitiveResolverStartAddressLookup},
	{"SocketPlugin", "primitiveResolverStartNameLookup", (void*)primitiveResolverStartNameLookup},
	{"SocketPlugin", "primitiveResolverStatus", (void*)primitiveResolverStatus},
	{"SocketPlugin", "primitiveSocketAbortConnection", (void*)primitiveSocketAbortConnection},
	{"SocketPlugin", "primitiveSocketAccept", (void*)primitiveSocketAccept},
	{"SocketPlugin", "primitiveSocketAccept3Semaphores", (void*)primitiveSocketAccept3Semaphores},
	{"SocketPlugin", "primitiveSocketAddressGetPort", (void*)primitiveSocketAddressGetPort},
	{"SocketPlugin", "primitiveSocketAddressSetPort", (void*)primitiveSocketAddressSetPort},
	{"SocketPlugin", "primitiveSocketBindTo", (void*)primitiveSocketBindTo},
	{"SocketPlugin", "primitiveSocketBindToPort", (void*)primitiveSocketBindToPort},
	{"SocketPlugin", "primitiveSocketCloseConnection", (void*)primitiveSocketCloseConnection},
	{"SocketPlugin", "primitiveSocketConnectionStatus", (void*)primitiveSocketConnectionStatus},
	{"SocketPlugin", "primitiveSocketConnectTo", (void*)primitiveSocketConnectTo},
	{"SocketPlugin", "primitiveSocketConnectToPort", (void*)primitiveSocketConnectToPort},
	{"SocketPlugin", "primitiveSocketCreate", (void*)primitiveSocketCreate},
	{"SocketPlugin", "primitiveSocketCreate3Semaphores", (void*)primitiveSocketCreate3Semaphores},
	{"SocketPlugin", "primitiveSocketDestroy", (void*)primitiveSocketDestroy},
	{"SocketPlugin", "primitiveSocketError", (void*)primitiveSocketError},
	{"SocketPlugin", "primitiveSocketGetOptions", (void*)primitiveSocketGetOptions},
	{"SocketPlugin", "primitiveSocketListenOnPort", (void*)primitiveSocketListenOnPort},
	{"SocketPlugin", "primitiveSocketListenOnPortBacklog", (void*)primitiveSocketListenOnPortBacklog},
	{"SocketPlugin", "primitiveSocketListenOnPortBacklogInterface", (void*)primitiveSocketListenOnPortBacklogInterface},
	{"SocketPlugin", "primitiveSocketListenWithBacklog", (void*)primitiveSocketListenWithBacklog},
	{"SocketPlugin", "primitiveSocketListenWithOrWithoutBacklog", (void*)primitiveSocketListenWithOrWithoutBacklog},
	{"SocketPlugin", "primitiveSocketLocalAddress", (void*)primitiveSocketLocalAddress},
	{"SocketPlugin", "primitiveSocketLocalAddressResult", (void*)primitiveSocketLocalAddressResult},
	{"SocketPlugin", "primitiveSocketLocalAddressSize", (void*)primitiveSocketLocalAddressSize},
	{"SocketPlugin", "primitiveSocketLocalPort", (void*)primitiveSocketLocalPort},
	{"SocketPlugin", "primitiveSocketReceiveDataAvailable", (void*)primitiveSocketReceiveDataAvailable},
	{"SocketPlugin", "primitiveSocketReceiveDataBufCount", (void*)primitiveSocketReceiveDataBufCount},
	{"SocketPlugin", "primitiveSocketReceiveUDPDataBufCount", (void*)primitiveSocketReceiveUDPDataBufCount},
	{"SocketPlugin", "primitiveSocketRemoteAddress", (void*)primitiveSocketRemoteAddress},
	{"SocketPlugin", "primitiveSocketRemoteAddressResult", (void*)primitiveSocketRemoteAddressResult},
	{"SocketPlugin", "primitiveSocketRemoteAddressSize", (void*)primitiveSocketRemoteAddressSize},
	{"SocketPlugin", "primitiveSocketRemotePort", (void*)primitiveSocketRemotePort},
	{"SocketPlugin", "primitiveSocketSCTPEnableDataIOEvent", (void*)primitiveSocketSCTPEnableDataIOEvent},
	{"SocketPlugin", "primitiveSocketSCTPReceive", (void*)primitiveSocketSCTPReceive},
	{"SocketPlugin", "primitiveSocketSCTPSend", (void*)primitiveSocketSCTPSend},
	{"SocketPlugin", "primitiveSocketSendDataBufCount", (void*)primitiveSocketSendDataBufCount},
	{"SocketPlugin", "primitiveSocketSendDone", (void*)primitiveSocketSendDone},
	{"SocketPlugin", "primitiveSocketSendUDPDataBufCount", (void*)primitiveSocketSendUDPDataBufCount},
	{"SocketPlugin", "primitiveSocketSetOptions", (void*)primitiveSocketSetOptions},
	{"SocketPlugin", "setInterpreter", (void*)setInterpreter},
	{"SocketPlugin", "shutdownModule", (void*)shutdownModule},
	{NULL, NULL, NULL}
};

#endif /* ifdef SQ_BUILTIN_PLUGIN */
